# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    - name: Upload artifact to enable deployment
      uses: actions/upload-artifact@v3
      with:
          name: production-files
          path: ./dist
          
  deploy:

      needs: build
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/main'
      steps:

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: production-files
          path: ./dist
          
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4.0.5
        with:
          # GitHub token
          token: ${{ secrets.TOKEN }}
          # Time in milliseconds after which to timeout and cancel the deployment (default: 10 minutes)
  
                
                  
